version: "2.18"

services:
  db:
    image: postgres:15.3-alpine
    container_name: "comments-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database-postgres:/var/lib/postgres/data

  api:
    build: .
    container_name: "comments-rest-api"
    environment:
      - DB_USERNAME: "postgres"
      - DB_PASSWORD: "postgres"
      - DB_DB: "postgres"
      - DB_HOST: "db"
      - DB_TABLE: "postgres"
      - DB_PORT: "5432"
      - SSL_MODE: "disable"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack
